services:
  data-base:
    image: postgres:14.6
    container_name: archiveDatabase
    environment:
      - POSTGRES_USER=archiveDatabase
      - POSTGRES_PASSWORD=archiveDatabase
      - POSTGRES_DB=archiveDatabase
    ports:
      - 5432:5432
    command: postgres -p 5432